-- Invoice workflow: payment tracking, audit trail, returns and offline sync metadata.
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  invoice_number text not null unique,
  customer_name text not null default '',
  customer_phone text not null default '',
  customer_address text not null default '',
  store_phone text not null default '',
  created_at timestamptz not null default now(),
  discount numeric not null default 0,
  total numeric not null default 0,
  items jsonb not null default '[]'::jsonb,
  notes text
);

alter table public.customer_orders
  add column if not exists invoice_status text not null default 'draft',
  add column if not exists paid_amount numeric not null default 0,
  add column if not exists payment_status text not null default 'unpaid',
  add column if not exists approved_at timestamptz,
  add column if not exists approved_by uuid references auth.users(id) on delete set null,
  add column if not exists offline_created_at timestamptz,
  add column if not exists last_synced_at timestamptz;

alter table public.invoices
  add column if not exists delivery_fee numeric not null default 0,
  add column if not exists payment_method text not null default 'cash_on_delivery',
  add column if not exists paid_amount numeric not null default 0,
  add column if not exists invoice_status text not null default 'draft',
  add column if not exists payment_status text not null default 'unpaid';

alter table public.customer_orders
  drop constraint if exists customer_orders_invoice_status_check;
alter table public.customer_orders
  add constraint customer_orders_invoice_status_check
  check (invoice_status in ('draft', 'pending_payment', 'paid', 'processing', 'completed', 'cancelled'));

alter table public.customer_orders
  drop constraint if exists customer_orders_payment_status_check;
alter table public.customer_orders
  add constraint customer_orders_payment_status_check
  check (payment_status in ('unpaid', 'partial', 'paid', 'refunded'));

create index if not exists customer_orders_invoice_status_idx
on public.customer_orders (user_id, invoice_status, created_at desc);

create table if not exists public.order_payments (
  id bigint generated by default as identity primary key,
  order_number text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric not null check (amount > 0),
  method text not null check (method in ('cash', 'bank_transfer', 'card', 'cash_on_delivery')),
  reference text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists order_payments_order_idx
on public.order_payments (user_id, order_number, created_at desc);
alter table public.order_payments enable row level security;
drop policy if exists "Users can manage order payments" on public.order_payments;
create policy "Users can manage order payments"
on public.order_payments for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.order_returns (
  id bigint generated by default as identity primary key,
  order_number text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  amount numeric not null default 0,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists order_returns_order_idx
on public.order_returns (user_id, order_number, created_at desc);
alter table public.order_returns enable row level security;
drop policy if exists "Users can manage order returns" on public.order_returns;
create policy "Users can manage order returns"
on public.order_returns for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.order_audit_log (
  id bigint generated by default as identity primary key,
  order_number text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_audit_order_idx
on public.order_audit_log (user_id, order_number, created_at desc);
alter table public.order_audit_log enable row level security;
drop policy if exists "Users can read order audit log" on public.order_audit_log;
create policy "Users can read order audit log"
on public.order_audit_log for select to authenticated
using (auth.uid() = user_id);
drop policy if exists "Users can create order audit log" on public.order_audit_log;
create policy "Users can create order audit log"
on public.order_audit_log for insert to authenticated
with check (auth.uid() = user_id);
