create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.customer_orders(id) on delete cascade,
  order_number text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null,
  changed_at timestamptz not null default now()
);

create index if not exists order_status_history_order_idx
on public.order_status_history (order_id, changed_at asc);

alter table public.order_status_history enable row level security;

drop policy if exists "Users can read their order status history" on public.order_status_history;
create policy "Users can read their order status history"
on public.order_status_history for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.record_order_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.order_status_history (
      order_id, order_number, user_id, status, changed_at
    ) values (
      new.id,
      new.order_number,
      new.user_id,
      new.status,
      coalesce(new.updated_at, new.created_at, now())
    );
  end if;
  return new;
end;
$$;

drop trigger if exists customer_orders_status_history on public.customer_orders;
create trigger customer_orders_status_history
after insert or update of status on public.customer_orders
for each row
execute function public.record_order_status_history();

insert into public.order_status_history (
  order_id, order_number, user_id, status, changed_at
)
select o.id, o.order_number, o.user_id, o.status, coalesce(o.updated_at, o.created_at, now())
from public.customer_orders o
where not exists (
  select 1
  from public.order_status_history h
  where h.order_id = o.id
);

drop function if exists public.get_public_order_tracking(text);

create or replace function public.get_public_order_tracking(p_order_number text)
returns table (
  order_number text,
  status text,
  created_at timestamptz,
  updated_at timestamptz,
  status_history jsonb
)
language sql
security definer
set search_path = public
as $$
  select
    o.order_number,
    o.status,
    o.created_at,
    o.updated_at,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'status', h.status,
            'changed_at', h.changed_at
          ) order by h.changed_at asc, h.id asc
        )
        from public.order_status_history h
        where h.order_id = o.id
      ),
      '[]'::jsonb
    ) as status_history
  from public.customer_orders o
  where upper(o.order_number) = upper(trim(p_order_number))
  limit 1;
$$;

grant execute on function public.get_public_order_tracking(text) to anon, authenticated;
