create table if not exists public.customer_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  store_user_id uuid references auth.users(id) on delete set null,
  order_number text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_landmark text not null default '',
  total_amount numeric not null default 0,
  status text not null default 'pending',
  payment_method text not null default 'cash_on_delivery',
  delivery_area text not null default 'baghdad',
  delivery_fee numeric not null default 0,
  receipt_number text,
  delivery_result text not null default 'pending',
  notes text,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists customer_orders_user_id_idx
on public.customer_orders (user_id, created_at desc);

create index if not exists customer_orders_store_user_id_idx
on public.customer_orders (store_user_id, created_at desc);

alter table public.customer_orders enable row level security;

drop policy if exists "Users can read their customer orders" on public.customer_orders;
create policy "Users can read their customer orders"
on public.customer_orders for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create their customer orders" on public.customer_orders;
create policy "Users can create their customer orders"
on public.customer_orders for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their customer orders" on public.customer_orders;
create policy "Users can update their customer orders"
on public.customer_orders for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
