name: Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href "/alnakhla/"

      - name: Add SEO and verification files
        run: |
          cp googleef05bf2a779b5a96.html build/web/googleef05bf2a779b5a96.html
          cp robots.txt build/web/robots.txt
          cp sitemap.xml build/web/sitemap.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
